// Linked after a 130 MiB filler (generated by the test), beyond the 128 MiB
// reach of an arm64 `bl` from main (far_main.c), which therefore needs a
// range-extension thunk.
int puts(const char *);

__attribute__((noinline)) int far_function(int x) {
    puts("far");
    return x + 1;
}
